services:
  mysql_db:
    image: mysql:5.7
    hostname: mysql_db
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: College
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - db_volume:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    stdin_open: true
    tty: true 
    depends_on:
      - mysql_db
    env_file:
      - .env
    ports:
      - "3001:3001"
    networks:
      - app-network
networks:
  app-network:
    external: true
volumes:
  db_volume:
    external: true