apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: db-app
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-test
  template:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
      - name: app-test
        image: yosepholiver/node-project:v1
        ports:
        - containerPort: 3001
        env:
        - name: DB_DATABASE
          value: "mysql://root:root@mysql:3306/db-app"
---
apiVersion: v1
kind: Service
metadata:
  name: app-test
spec:
  selector:
    app: app-test
  ports:
  - port: 80
    targetPort: 3001
    nodePort: 30000
  type: NodePort
  